import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faFacebook, faInstagram, faXTwitter, faLinkedin } from "@fortawesome/free-brands-svg-icons";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Whizz Dream Big",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-white min-h-screen font-sans">
        <header className="bg-gray-100 text-purple-900 shadow-md sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-6 py-4 flex flex-col sm:flex-row items-center justify-between space-y-2 sm:space-y-0">
            <div className="flex items-center space-x-4">
              <img src="\images\Logo.jpg" alt="Whizz Dream innovation" className="h-16 w-16 object-contain" />
              <h1 className="text-xl sm:text-2xl font-bold text-center sm:text-left">Whizz Dream Innovation</h1>
            </div>
            <nav className="space-x-4 text-center sm:text-right">
              <a href="/" className="hover:text-blue-700">Home</a>
              <a href="/services" className="hover:text-blue-700">Services</a>
              <a href="/about" className="hover:text-blue-700">About</a>
              <a href="/contact" className="hover:text-blue-700">Contact</a>
            </nav>
          </div>
        </header>
      
        {children}

        <footer className="text-center py-6 shadow-[-4px_-4px_10px_rgba(0,0,0,0.1)]">
          <div className="py-5 px-10 flex items-center justify-between">
            <img src="/images/Logo.jpg" className="h-25 w-35" />
            <div className="flex gap-5">
              <a href="/" className="text-[#53197d] hover:text-blue-900 underline">Home</a>
              <a href="/services" className="text-[#53197d] hover:text-blue-900 underline">Services</a>
              <a href="/about" className="text-[#53197d] hover:text-blue-900 underline">About</a>
              <a href="/contact" className="text-[#53197d] hover:text-blue-900 underline">Contact</a>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <a href="/"><FontAwesomeIcon icon={faInstagram} className="h-8 hover:text-blue-900 text-[#53197d]" /></a>
              <a href="/"><FontAwesomeIcon icon={faFacebook} className="h-8 hover:text-blue-900 text-[#53197d]" /></a>
              <a href="/"><FontAwesomeIcon icon={faXTwitter} className="h-8 hover:text-blue-900 text-[#53197d]" /></a>
              <a href="/"><FontAwesomeIcon icon={faLinkedin} className="h-8 hover:text-blue-900 text-[#53197d]" /></a>
            </div>
          </div>
          <div className="text-black">
            &copy; 2025 Whizz Dream Big. All rights reserved.
          </div>
        </footer>

      </body>
    </html>
  );
}
